image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: only  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

script:
  - npm run lint && npm test  # скрипт тестирования 